<?php
	class Colors {
		private $foreground_colors = array();
		private $background_colors = array();

		public function __construct() {
			// Set up shell colors
			$this->foreground_colors['black'] = '0;30';
			$this->foreground_colors['dark_gray'] = '1;30';
			$this->foreground_colors['blue'] = '0;34';
			$this->foreground_colors['light_blue'] = '1;34';
			$this->foreground_colors['green'] = '0;32';
			$this->foreground_colors['light_green'] = '1;32';
			$this->foreground_colors['cyan'] = '0;36';
			$this->foreground_colors['light_cyan'] = '1;36';
			$this->foreground_colors['red'] = '0;31';
			$this->foreground_colors['light_red'] = '1;31';
			$this->foreground_colors['purple'] = '0;35';
			$this->foreground_colors['light_purple'] = '1;35';
			$this->foreground_colors['brown'] = '0;33';
			$this->foreground_colors['yellow'] = '1;33';
			$this->foreground_colors['light_gray'] = '0;37';
			$this->foreground_colors['white'] = '1;37';

			$this->background_colors['black'] = '40';
			$this->background_colors['red'] = '41';
			$this->background_colors['green'] = '42';
			$this->background_colors['yellow'] = '43';
			$this->background_colors['blue'] = '44';
			$this->background_colors['magenta'] = '45';
			$this->background_colors['cyan'] = '46';
			$this->background_colors['light_gray'] = '47';
		}

		// Returns colored string
		public function getColoredString($string, $foreground_color = null, $background_color = null) {
			$colored_string = "";

			// Check if given foreground color found
			if (isset($this->foreground_colors[$foreground_color])) {
				$colored_string .= "\033[" . $this->foreground_colors[$foreground_color] . "m";
			}
			// Check if given background color found
			if (isset($this->background_colors[$background_color])) {
				$colored_string .= "\033[" . $this->background_colors[$background_color] . "m";
			}

			// Add string and end coloring
			$colored_string .=  $string . "\033[0m";

			return $colored_string;
		}

		// Returns all foreground color names
		public function getForegroundColors() {
			return array_keys($this->foreground_colors);
		}

		// Returns all background color names
		public function getBackgroundColors() {
			return array_keys($this->background_colors);
		}
    }

    $colors = new Colors();
echo "
             " . $colors->getColoredString("__________________", "blue") . $colors->getColoredString("    .============.         ", "yellow") . $colors->getColoredString("__________________", "red") . $colors->getColoredString("    .==========.           ", "yellow") . $colors->getColoredString("__________________", "cyan") . $colors->getColoredString("    .===========.           ", "yellow") . $colors->getColoredString("__________________", "purple") . $colors->getColoredString("    .==================.    ", "yellow") . "
            " . $colors->getColoredString("/", "blue") . $colors->getColoredString(" __/\/,\__       ", "yellow") . $colors->getColoredString("/|", "blue") . $colors->getColoredString(".-[ ", "yellow") . "pour Maxime! " . $colors->getColoredString("]", "yellow") . "       " . $colors->getColoredString("/ ", "red") . $colors->getColoredString("__/\/,\__       ", "yellow") . $colors->getColoredString("/|", "red") . $colors->getColoredString(".-[", "yellow") . " pour Nico! " . $colors->getColoredString("]", "yellow") . "         " . $colors->getColoredString("/", "cyan") . $colors->getColoredString(" __/\/,\__       ", "yellow") . $colors->getColoredString("/|", "cyan") . $colors->getColoredString(".-[", "yellow") . " pour Alice! " . $colors->getColoredString("]", "yellow") . "         " . $colors->getColoredString("/ " , "purple") . $colors->getColoredString("__/\/,\__       ", "yellow") . $colors->getColoredString("/|" , "purple") . $colors->getColoredString(".-[", "yellow") . " pour Christilline! " . $colors->getColoredString("]", "yellow") . "   
           " . $colors->getColoredString(",==", "red") . $colors->getColoredString("\_\_\_/_/", "yellow") . $colors->getColoredString("======,", "red"). $colors->getColoredString("./   '============'       ", "yellow") . $colors->getColoredString(",==", "blue") . $colors->getColoredString("\_\_\_/_/", "yellow") . $colors->getColoredString("======,", "blue") . $colors->getColoredString("./   '=========='         ", "yellow") . $colors->getColoredString(",==", "purple") . $colors->getColoredString("\_\_\_/_/", "yellow") . $colors->getColoredString("======,", "purple") . $colors->getColoredString("./   '==========='         ", "yellow") . $colors->getColoredString(",==", "cyan") . $colors->getColoredString("\_\_\_/_/", "yellow") . $colors->getColoredString("======,", "cyan") . $colors->getColoredString("./   '=================='    ", "yellow") . "
          " . $colors->getColoredString("/~~", "red") . $colors->getColoredString("<__((_))__>", "yellow") . $colors->getColoredString("~~~~/| ", "red") . $colors->getColoredString("|", "blue") . "                       " . $colors->getColoredString("/~~" , "blue") . $colors->getColoredString("<__((_))__>", "yellow") . $colors->getColoredString("~~~~/|", "blue") .$colors->getColoredString(" |                       ", "red") . $colors->getColoredString("/~~", "purple") . $colors->getColoredString("<__((_))__>", "yellow") . $colors->getColoredString("~~~~/| ", "purple") . $colors->getColoredString("|                        ", "cyan") . $colors->getColoredString("/~~", "cyan") . $colors->getColoredString("<__((_))__>", "yellow") . $colors->getColoredString("~~~~/| ", "cyan") . $colors->getColoredString("|", "purple") . "                           
         " . $colors->getColoredString(",====", "red"). $colors->getColoredString("\_/\_\`_/", "yellow") . $colors->getColoredString("====,§| ", "red") . $colors->getColoredString("|", "blue") . $colors->getColoredString("                      ,====", "blue") . $colors->getColoredString("\_/\_\`_/", "yellow") . $colors->getColoredString("====,§| ", "blue") . $colors->getColoredString("|                      ", "red") . $colors->getColoredString("/====", "purple") . $colors->getColoredString("\_/\_\`_/", "yellow") . $colors->getColoredString("====,§| ", "purple") . $colors->getColoredString("|", "cyan") . $colors->getColoredString("                       ,====", "cyan") . $colors->getColoredString("\_/\_\`_/", "yellow") . $colors->getColoredString("====,§| ", "cyan") . $colors->getColoredString("|", "purple") . "                           
        " . $colors->getColoredString("/", "blue") . $colors->getColoredString("      / /\ \     ", "yellow") . $colors->getColoredString("/", "blue") . $colors->getColoredString("|§|/'", "red") . $colors->getColoredString("                     /      ", "red") . $colors->getColoredString("/ /\ \     ", "yellow") . $colors->getColoredString("/", "red") . $colors->getColoredString("|§|/'", "blue") . $colors->getColoredString("                     /", "cyan") . $colors->getColoredString("      / /\ \     ", "yellow") . $colors->getColoredString("/", "cyan") . $colors->getColoredString("|§|/'", "purple") . $colors->getColoredString("                      /", "purple") . $colors->getColoredString("      / /\ \     ", "yellow") . $colors->getColoredString("/", "purple") . $colors->getColoredString("|§|/'", "cyan") . "                           
       ". $colors->getColoredString(".------", "blue") . $colors->getColoredString("/ /", "yellow") . $colors->getColoredString("==", "red") . $colors->getColoredString("\ \\", "yellow") . $colors->getColoredString("---.", "blue") . $colors->getColoredString(" |§/ |", "red") . $colors->getColoredString("                    .------", "red") . $colors->getColoredString("/ /", "yellow") . $colors->getColoredString("==", "blue") . $colors->getColoredString("\ \\", "yellow") . $colors->getColoredString("---. ", "red") . $colors->getColoredString("|§/ |", "blue") . $colors->getColoredString("                    .------", "cyan") . $colors->getColoredString("/ /", "yellow"). $colors->getColoredString("==", "purple") . $colors->getColoredString("\ \\", "yellow") . $colors->getColoredString("---. ", "cyan") . $colors->getColoredString("|§/ |", "purple") . $colors->getColoredString("                     .------", "purple") . $colors->getColoredString("/ /", "yellow") . $colors->getColoredString("==", "cyan") . $colors->getColoredString("\ \\", "yellow") . $colors->getColoredString("---. ", "purple") . $colors->getColoredString("|§/ |", "cyan") . "                        
       " . $colors->getColoredString("|      ", "blue") . $colors->getColoredString("V'", "yellow") . $colors->getColoredString("§||", "red") . $colors->getColoredString(" | |  ", "yellow") . $colors->getColoredString("| ", "blue") . $colors->getColoredString("|/  ,", "red") . $colors->getColoredString("                    |      ", "red") . $colors->getColoredString("V'", "yellow") . $colors->getColoredString("§|| ", "blue") . $colors->getColoredString("| |  ", "yellow") . $colors->getColoredString("| ", "red") . $colors->getColoredString("|/  ,", "blue") . $colors->getColoredString("                    |      ", "cyan") . $colors->getColoredString("V'", "yellow") . $colors->getColoredString("§|| ", "purple") . $colors->getColoredString("| |  ", "yellow") . $colors->getColoredString("| ", "cyan") . $colors->getColoredString("|/  ,", "purple") . $colors->getColoredString("                     |      ", "purple") . $colors->getColoredString("V'", "yellow") . $colors->getColoredString("§|| ", "cyan") . $colors->getColoredString("| |  ", "yellow") . $colors->getColoredString("| ", "purple") . $colors->getColoredString("|/  ,", "cyan") . "                           
       " . $colors->getColoredString("|      ", "blue") . $colors->getColoredString("||§||  ", "red") . $colors->getColoredString("V", "yellow") . $colors->getColoredString("   | ", "blue") . $colors->getColoredString("/  /", "red") . $colors->getColoredString("|                    ", "blue") . $colors->getColoredString("|      ", "red") . $colors->getColoredString("||§||  ", "blue") . $colors->getColoredString("V   ", "yellow") . $colors->getColoredString("| ", "red") . $colors->getColoredString("/  /", "blue") . $colors->getColoredString("|                    ", "red") . $colors->getColoredString("|      ", "cyan") . $colors->getColoredString("||§||  ", "purple") . $colors->getColoredString("V   ", "yellow") . $colors->getColoredString("| ", "cyan") . $colors->getColoredString("/  /", "purple") . $colors->getColoredString("|                     ", "cyan") . $colors->getColoredString("|      ", "purple") . $colors->getColoredString("||§||  ", "cyan") . $colors->getColoredString("V   ", "yellow") . $colors->getColoredString("| ", "purple") . $colors->getColoredString("/  /", "cyan") . $colors->getColoredString("|", "purple") . "                           
       " . $colors->getColoredString("|      ", "blue") . $colors->getColoredString("||§||      ", "red") . $colors->getColoredString("|", "blue") . $colors->getColoredString("/  / ", "red") . $colors->getColoredString("|                    ", "blue") . $colors->getColoredString("|      ", "red") . $colors->getColoredString("||§||      ", "blue") . $colors->getColoredString("|", "red") . $colors->getColoredString("/  / ", "blue") . $colors->getColoredString("|                    ", "red") . $colors->getColoredString("|      ", "cyan") . $colors->getColoredString("||§||      ", "purple") . $colors->getColoredString("|", "cyan") . $colors->getColoredString("/  / ", "purple") . $colors->getColoredString("|                     ", "cyan") . $colors->getColoredString("|      ", "purple") . $colors->getColoredString("||§||      ", "cyan") . $colors->getColoredString("|", "purple") . $colors->getColoredString("/  / ", "cyan") . $colors->getColoredString("|", "purple") . "                           
       " . $colors->getColoredString(",=================,", "red") . $colors->getColoredString("  /| ", "red") .$colors->getColoredString("|                    ", "blue") . $colors->getColoredString(",=================,", "blue") . $colors->getColoredString("  /| ", "blue") . $colors->getColoredString("|                    ", "red") . $colors->getColoredString(",=================,", "purple") . $colors->getColoredString("  /| ", "purple") . $colors->getColoredString("|                     ", "cyan") . $colors->getColoredString(",=================,", "cyan") . $colors->getColoredString("  /| ", "cyan") . $colors->getColoredString("|", "purple") . "                           
       " . $colors->getColoredString("|                 | /§|", "red") . $colors->getColoredString("/                     ", "blue") . $colors->getColoredString("|                 | /§|", "blue") . $colors->getColoredString("/                     ", "red") . $colors->getColoredString("|                 | /§|", "purple") . $colors->getColoredString("/                      ", "cyan") . $colors->getColoredString("|                 | /§|", "cyan") . $colors->getColoredString("/", "purple") . "                            
       " . $colors->getColoredString("`=================`", "red") . $colors->getColoredString("/|§", "red") . $colors->getColoredString("/                      ", "blue") . $colors->getColoredString("`=================`", "blue") . $colors->getColoredString("/|§", "blue") . $colors->getColoredString("/                      ", "red") . $colors->getColoredString("`=================`", "purple") . $colors->getColoredString("/|§", "purple") .$colors->getColoredString("/                       ", "cyan") . $colors->getColoredString("`=================`", "cyan") . $colors->getColoredString("/|§", "cyan") . $colors->getColoredString("/", "purple") . "                             
       " . $colors->getColoredString("|      ", "blue") . $colors->getColoredString("||§||      ", "red") . $colors->getColoredString("| ", "blue") . $colors->getColoredString("|", "red") . $colors->getColoredString("/                       ", "blue") . $colors->getColoredString("|      ", "red") . $colors->getColoredString("||§||      ", "blue") . $colors->getColoredString("| ", "red") . $colors->getColoredString("|", "blue") . $colors->getColoredString("/                       ", "red") . $colors->getColoredString("|      ", "cyan") . $colors->getColoredString("||§||      ", "purple") . $colors->getColoredString("| ", "cyan") . $colors->getColoredString("|", "purple") . $colors->getColoredString("/                        ", "cyan") . $colors->getColoredString("|      ", "purple") . $colors->getColoredString("||§||      ", "cyan") . $colors->getColoredString("| ", "purple") . $colors->getColoredString("|", "cyan") . $colors->getColoredString("/", "purple") . "                              
       " . $colors->getColoredString("|      ", "blue") . $colors->getColoredString("||§||      ", "red") . $colors->getColoredString("| /                        ", "blue") . $colors->getColoredString("|      ", "red") . $colors->getColoredString("||§||      ", "blue") . $colors->getColoredString("| /                        ", "red") . $colors->getColoredString("|      ", "blue") . $colors->getColoredString("||§||      ", "purple") . $colors->getColoredString("| /                         ", "cyan") . $colors->getColoredString("|      ", "purple") . $colors->getColoredString("||§||      ", "cyan") . $colors->getColoredString("| /", "purple") . "                               
       " . $colors->getColoredString("|      ", "blue") . $colors->getColoredString("||§||      ", "red") . $colors->getColoredString("|/                         ", "blue") . $colors->getColoredString("|      ", "red") . $colors->getColoredString("||§||      ", "blue") . $colors->getColoredString("|/                         ", "red") . $colors->getColoredString("|      ", "cyan") . $colors->getColoredString("||§||      ", "purple") . $colors->getColoredString("|/                          ", "cyan") . $colors->getColoredString("|      ", "purple") . $colors->getColoredString("||§||      ", "cyan") . $colors->getColoredString("|/", "purple") . "                                
       ". $colors->getColoredString("'------", "blue") . $colors->getColoredString("=====", "red") . $colors->getColoredString("------'                          ", "blue") . $colors->getColoredString("'------", "red") . $colors->getColoredString("=====", "blue") . $colors->getColoredString("------'                          ", "red") . $colors->getColoredString("'------", "cyan") . $colors->getColoredString("=====", "purple") . $colors->getColoredString("------'                           ", "cyan") . $colors->getColoredString("'------", "purple") . $colors->getColoredString("=====", "cyan") . $colors->getColoredString("------'", "purple") . "                                 
	             " . $colors->getColoredString("__________________", "light_purple") . $colors->getColoredString("    .=============.        ", "yellow") . $colors->getColoredString("__________________", "white") . $colors->getColoredString("    .==========.           ", "yellow") . $colors->getColoredString("__________________", "purple") . $colors->getColoredString("    .===========.           ", "yellow") . $colors->getColoredString("__________________", "light_green") . $colors->getColoredString("    .=============.    ", "yellow") . "
	            " . $colors->getColoredString("/", "light_purple") . $colors->getColoredString(" __/\/,\__       ", "yellow") . $colors->getColoredString("/|", "light_purple") . $colors->getColoredString(".-[ ", "yellow") . "pour Camille! " . $colors->getColoredString("]", "yellow") . "      " . $colors->getColoredString("/ ", "white") . $colors->getColoredString("__/\/,\__       ", "yellow") . $colors->getColoredString("/|", "white") . $colors->getColoredString(".-[", "yellow") . " pour Dany! " . $colors->getColoredString("]", "yellow") . "         " . $colors->getColoredString("/", "purple") . $colors->getColoredString(" __/\/,\__       ", "yellow") . $colors->getColoredString("/|", "purple") . $colors->getColoredString(".-[", "yellow") . " pour Diego! " . $colors->getColoredString("]", "yellow") . "         " . $colors->getColoredString("/ " , "light_green") . $colors->getColoredString("__/\/,\__       ", "yellow") . $colors->getColoredString("/|" , "light_green") . $colors->getColoredString(".-[", "yellow") . " pour Justine! " . $colors->getColoredString("]", "yellow") . "   
	           " . $colors->getColoredString(",==", "white") . $colors->getColoredString("\_\_\_/_/", "yellow") . $colors->getColoredString("======,", "white"). $colors->getColoredString("./   '============='      ", "yellow") . $colors->getColoredString(",==", "light_purple") . $colors->getColoredString("\_\_\_/_/", "yellow") . $colors->getColoredString("======,", "light_purple") . $colors->getColoredString("./   '=========='         ", "yellow") . $colors->getColoredString(",==", "light_green") . $colors->getColoredString("\_\_\_/_/", "yellow") . $colors->getColoredString("======,", "light_green") . $colors->getColoredString("./   '==========='         ", "yellow") . $colors->getColoredString(",==", "purple") . $colors->getColoredString("\_\_\_/_/", "yellow") . $colors->getColoredString("======,", "purple") . $colors->getColoredString("./   '============='    ", "yellow") . "
	          " . $colors->getColoredString("/~~", "white") . $colors->getColoredString("<__((_))__>", "yellow") . $colors->getColoredString("~~~~/| ", "white") . $colors->getColoredString("|", "light_purple") . "                       " . $colors->getColoredString("/~~" , "light_purple") . $colors->getColoredString("<__((_))__>", "yellow") . $colors->getColoredString("~~~~/|", "light_purple") .$colors->getColoredString(" |                       ", "white") . $colors->getColoredString("/~~", "light_green") . $colors->getColoredString("<__((_))__>", "yellow") . $colors->getColoredString("~~~~/| ", "light_green") . $colors->getColoredString("|                        ", "purple") . $colors->getColoredString("/~~", "purple") . $colors->getColoredString("<__((_))__>", "yellow") . $colors->getColoredString("~~~~/| ", "purple") . $colors->getColoredString("|", "light_green") . "                           
	         " . $colors->getColoredString(",====", "white"). $colors->getColoredString("\_/\_\`_/", "yellow") . $colors->getColoredString("====,§| ", "white") . $colors->getColoredString("|", "light_purple") . $colors->getColoredString("                      ,====", "light_purple") . $colors->getColoredString("\_/\_\`_/", "yellow") . $colors->getColoredString("====,§| ", "light_purple") . $colors->getColoredString("|                      ", "white") . $colors->getColoredString("/====", "light_green") . $colors->getColoredString("\_/\_\`_/", "yellow") . $colors->getColoredString("====,§| ", "light_green") . $colors->getColoredString("|", "purple") . $colors->getColoredString("                       ,====", "purple") . $colors->getColoredString("\_/\_\`_/", "yellow") . $colors->getColoredString("====,§| ", "purple") . $colors->getColoredString("|", "light_green") . "                           
	        " . $colors->getColoredString("/", "light_purple") . $colors->getColoredString("      / /\ \     ", "yellow") . $colors->getColoredString("/", "light_purple") . $colors->getColoredString("|§|/'", "white") . $colors->getColoredString("                     /      ", "white") . $colors->getColoredString("/ /\ \     ", "yellow") . $colors->getColoredString("/", "white") . $colors->getColoredString("|§|/'", "light_purple") . $colors->getColoredString("                     /", "purple") . $colors->getColoredString("      / /\ \     ", "yellow") . $colors->getColoredString("/", "purple") . $colors->getColoredString("|§|/'", "light_green") . $colors->getColoredString("                      /", "light_green") . $colors->getColoredString("      / /\ \     ", "yellow") . $colors->getColoredString("/", "light_green") . $colors->getColoredString("|§|/'", "purple") . "                           
               ". $colors->getColoredString(".------", "light_purple") . $colors->getColoredString("/ /", "yellow") . $colors->getColoredString("==", "white") . $colors->getColoredString("\ \\", "yellow") . $colors->getColoredString("---.", "light_purple") . $colors->getColoredString(" |§/ |", "white") . $colors->getColoredString("                    .------", "white") . $colors->getColoredString("/ /", "yellow") . $colors->getColoredString("==", "light_purple") . $colors->getColoredString("\ \\", "yellow") . $colors->getColoredString("---. ", "white") . $colors->getColoredString("|§/ |", "light_purple") . $colors->getColoredString("                    .------", "purple") . $colors->getColoredString("/ /", "yellow"). $colors->getColoredString("==", "light_green") . $colors->getColoredString("\ \\", "yellow") . $colors->getColoredString("---. ", "purple") . $colors->getColoredString("|§/ |", "light_green") . $colors->getColoredString("                     .------", "light_green") . $colors->getColoredString("/ /", "yellow") . $colors->getColoredString("==", "purple") . $colors->getColoredString("\ \\", "yellow") . $colors->getColoredString("---. ", "light_green") . $colors->getColoredString("|§/ |", "purple") . "                        
	       " . $colors->getColoredString("|      ", "light_purple") . $colors->getColoredString("V'", "yellow") . $colors->getColoredString("§||", "white") . $colors->getColoredString(" | |  ", "yellow") . $colors->getColoredString("| ", "light_purple") . $colors->getColoredString("|/  ,", "white") . $colors->getColoredString("                    |      ", "white") . $colors->getColoredString("V'", "yellow") . $colors->getColoredString("§|| ", "light_purple") . $colors->getColoredString("| |  ", "yellow") . $colors->getColoredString("| ", "white") . $colors->getColoredString("|/  ,", "light_purple") . $colors->getColoredString("                    |      ", "purple") . $colors->getColoredString("V'", "yellow") . $colors->getColoredString("§|| ", "light_green") . $colors->getColoredString("| |  ", "yellow") . $colors->getColoredString("| ", "purple") . $colors->getColoredString("|/  ,", "light_green") . $colors->getColoredString("                     |      ", "light_green") . $colors->getColoredString("V'", "yellow") . $colors->getColoredString("§|| ", "purple") . $colors->getColoredString("| |  ", "yellow") . $colors->getColoredString("| ", "light_green") . $colors->getColoredString("|/  ,", "purple") . "                           
	       " . $colors->getColoredString("|      ", "light_purple") . $colors->getColoredString("||§||  ", "white") . $colors->getColoredString("V", "yellow") . $colors->getColoredString("   | ", "light_purple") . $colors->getColoredString("/  /", "white") . $colors->getColoredString("|                    ", "light_purple") . $colors->getColoredString("|      ", "white") . $colors->getColoredString("||§||  ", "light_purple") . $colors->getColoredString("V   ", "yellow") . $colors->getColoredString("| ", "white") . $colors->getColoredString("/  /", "light_purple") . $colors->getColoredString("|                    ", "white") . $colors->getColoredString("|      ", "purple") . $colors->getColoredString("||§||  ", "light_green") . $colors->getColoredString("V   ", "yellow") . $colors->getColoredString("| ", "purple") . $colors->getColoredString("/  /", "light_green") . $colors->getColoredString("|                     ", "purple") . $colors->getColoredString("|      ", "light_green") . $colors->getColoredString("||§||  ", "purple") . $colors->getColoredString("V   ", "yellow") . $colors->getColoredString("| ", "light_green") . $colors->getColoredString("/  /", "purple") . $colors->getColoredString("|", "light_green") . "                           
	       " . $colors->getColoredString("|      ", "light_purple") . $colors->getColoredString("||§||      ", "white") . $colors->getColoredString("|", "light_purple") . $colors->getColoredString("/  / ", "white") . $colors->getColoredString("|                    ", "light_purple") . $colors->getColoredString("|      ", "white") . $colors->getColoredString("||§||      ", "light_purple") . $colors->getColoredString("|", "white") . $colors->getColoredString("/  / ", "light_purple") . $colors->getColoredString("|                    ", "white") . $colors->getColoredString("|      ", "purple") . $colors->getColoredString("||§||      ", "light_green") . $colors->getColoredString("|", "purple") . $colors->getColoredString("/  / ", "light_green") . $colors->getColoredString("|                     ", "purple") . $colors->getColoredString("|      ", "light_green") . $colors->getColoredString("||§||      ", "purple") . $colors->getColoredString("|", "light_green") . $colors->getColoredString("/  / ", "purple") . $colors->getColoredString("|", "light_green") . "                           
	       " . $colors->getColoredString(",=================,", "white") . $colors->getColoredString("  /| ", "white") .$colors->getColoredString("|                    ", "light_purple") . $colors->getColoredString(",=================,", "light_purple") . $colors->getColoredString("  /| ", "light_purple") . $colors->getColoredString("|                    ", "white") . $colors->getColoredString(",=================,", "light_green") . $colors->getColoredString("  /| ", "light_green") . $colors->getColoredString("|                     ", "purple") . $colors->getColoredString(",=================,", "purple") . $colors->getColoredString("  /| ", "purple") . $colors->getColoredString("|", "light_green") . "                           
	       " . $colors->getColoredString("|                 | /§|", "white") . $colors->getColoredString("/                     ", "light_purple") . $colors->getColoredString("|                 | /§|", "light_purple") . $colors->getColoredString("/                     ", "white") . $colors->getColoredString("|                 | /§|", "light_green") . $colors->getColoredString("/                      ", "purple") . $colors->getColoredString("|                 | /§|", "purple") . $colors->getColoredString("/", "light_green") . "                            
	       " . $colors->getColoredString("`=================`", "white") . $colors->getColoredString("/|§", "white") . $colors->getColoredString("/                      ", "light_purple") . $colors->getColoredString("`=================`", "light_purple") . $colors->getColoredString("/|§", "light_purple") . $colors->getColoredString("/                      ", "white") . $colors->getColoredString("`=================`", "light_green") . $colors->getColoredString("/|§", "light_green") .$colors->getColoredString("/                       ", "purple") . $colors->getColoredString("`=================`", "purple") . $colors->getColoredString("/|§", "purple") . $colors->getColoredString("/", "light_green") . "                             
	       " . $colors->getColoredString("|      ", "light_purple") . $colors->getColoredString("||§||      ", "white") . $colors->getColoredString("| ", "light_purple") . $colors->getColoredString("|", "white") . $colors->getColoredString("/                       ", "light_purple") . $colors->getColoredString("|      ", "white") . $colors->getColoredString("||§||      ", "light_purple") . $colors->getColoredString("| ", "white") . $colors->getColoredString("|", "light_purple") . $colors->getColoredString("/                       ", "white") . $colors->getColoredString("|      ", "purple") . $colors->getColoredString("||§||      ", "light_green") . $colors->getColoredString("| ", "purple") . $colors->getColoredString("|", "light_green") . $colors->getColoredString("/                        ", "purple") . $colors->getColoredString("|      ", "light_green") . $colors->getColoredString("||§||      ", "purple") . $colors->getColoredString("| ", "light_green") . $colors->getColoredString("|", "purple") . $colors->getColoredString("/", "light_green") . "                              
	       " . $colors->getColoredString("|      ", "light_purple") . $colors->getColoredString("||§||      ", "white") . $colors->getColoredString("| /                        ", "light_purple") . $colors->getColoredString("|      ", "white") . $colors->getColoredString("||§||      ", "light_purple") . $colors->getColoredString("| /                        ", "white") . $colors->getColoredString("|      ", "light_purple") . $colors->getColoredString("||§||      ", "light_green") . $colors->getColoredString("| /                         ", "purple") . $colors->getColoredString("|      ", "light_green") . $colors->getColoredString("||§||      ", "purple") . $colors->getColoredString("| /", "light_green") . "                               
	       " . $colors->getColoredString("|      ", "light_purple") . $colors->getColoredString("||§||      ", "white") . $colors->getColoredString("|/                         ", "light_purple") . $colors->getColoredString("|      ", "white") . $colors->getColoredString("||§||      ", "light_purple") . $colors->getColoredString("|/                         ", "white") . $colors->getColoredString("|      ", "purple") . $colors->getColoredString("||§||      ", "light_green") . $colors->getColoredString("|/                          ", "purple") . $colors->getColoredString("|      ", "light_green") . $colors->getColoredString("||§||      ", "purple") . $colors->getColoredString("|/", "light_green") . "                                
	       ". $colors->getColoredString("'------", "light_purple") . $colors->getColoredString("=====", "white") . $colors->getColoredString("------'                          ", "light_purple") . $colors->getColoredString("'------", "white") . $colors->getColoredString("=====", "light_purple") . $colors->getColoredString("------'                          ", "white") . $colors->getColoredString("'------", "purple") . $colors->getColoredString("=====", "light_green") . $colors->getColoredString("------'                           ", "purple") . $colors->getColoredString("'------", "light_green") . $colors->getColoredString("=====", "purple") . $colors->getColoredString("------'", "light_green") . "                                 



	    " . $colors->getColoredString("__________________", "blue") . $colors->getColoredString("    .==============.       ", "yellow") . $colors->getColoredString("__________________", "green") . $colors->getColoredString("    .==========.           ", "yellow") . $colors->getColoredString("__________________", "cyan") . $colors->getColoredString("    .============.          ", "yellow") . $colors->getColoredString("__________________", "light_red") . $colors->getColoredString("    .=============.    ", "yellow") . "
	   " . $colors->getColoredString("/", "blue") . $colors->getColoredString(" __/\/,\__       ", "yellow") . $colors->getColoredString("/|", "blue") . $colors->getColoredString(".-[ ", "yellow") . "pour Aurélien! " . $colors->getColoredString("]", "yellow") . "     " . $colors->getColoredString("/ ", "green") . $colors->getColoredString("__/\/,\__       ", "yellow") . $colors->getColoredString("/|", "green") . $colors->getColoredString(".-[", "yellow") . " pour Axel! " . $colors->getColoredString("]", "yellow") . "         " . $colors->getColoredString("/", "cyan") . $colors->getColoredString(" __/\/,\__       ", "yellow") . $colors->getColoredString("/|", "cyan") . $colors->getColoredString(".-[", "yellow") . " pour Amanda! " . $colors->getColoredString("]", "yellow") . "        " . $colors->getColoredString("/ " , "light_red") . $colors->getColoredString("__/\/,\__       ", "yellow") . $colors->getColoredString("/|" , "light_red") . $colors->getColoredString(".-[", "yellow") . " pour Anthony! " . $colors->getColoredString("]", "yellow") . "   
          " . $colors->getColoredString(",==", "green") . $colors->getColoredString("\_\_\_/_/", "yellow") . $colors->getColoredString("======,", "green"). $colors->getColoredString("./   '=============='     ", "yellow") . $colors->getColoredString(",==", "blue") . $colors->getColoredString("\_\_\_/_/", "yellow") . $colors->getColoredString("======,", "blue") . $colors->getColoredString("./   '=========='         ", "yellow") . $colors->getColoredString(",==", "light_red") . $colors->getColoredString("\_\_\_/_/", "yellow") . $colors->getColoredString("======,", "light_red") . $colors->getColoredString("./   '============'        ", "yellow") . $colors->getColoredString(",==", "cyan") . $colors->getColoredString("\_\_\_/_/", "yellow") . $colors->getColoredString("======,", "cyan") . $colors->getColoredString("./   '============='    ", "yellow") . "
         " . $colors->getColoredString("/~~", "green") . $colors->getColoredString("<__((_))__>", "yellow") . $colors->getColoredString("~~~~/| ", "green") . $colors->getColoredString("|", "blue") . "                       " . $colors->getColoredString("/~~" , "blue") . $colors->getColoredString("<__((_))__>", "yellow") . $colors->getColoredString("~~~~/|", "blue") .$colors->getColoredString(" |                       ", "green") . $colors->getColoredString("/~~", "light_red") . $colors->getColoredString("<__((_))__>", "yellow") . $colors->getColoredString("~~~~/| ", "light_red") . $colors->getColoredString("|                        ", "cyan") . $colors->getColoredString("/~~", "cyan") . $colors->getColoredString("<__((_))__>", "yellow") . $colors->getColoredString("~~~~/| ", "cyan") . $colors->getColoredString("|", "light_red") . "                           
        " . $colors->getColoredString(",====", "green"). $colors->getColoredString("\_/\_\`_/", "yellow") . $colors->getColoredString("====,§| ", "green") . $colors->getColoredString("|", "blue") . $colors->getColoredString("                      ,====", "blue") . $colors->getColoredString("\_/\_\`_/", "yellow") . $colors->getColoredString("====,§| ", "blue") . $colors->getColoredString("|                      ", "green") . $colors->getColoredString("/====", "light_red") . $colors->getColoredString("\_/\_\`_/", "yellow") . $colors->getColoredString("====,§| ", "light_red") . $colors->getColoredString("|", "cyan") . $colors->getColoredString("                       ,====", "cyan") . $colors->getColoredString("\_/\_\`_/", "yellow") . $colors->getColoredString("====,§| ", "cyan") . $colors->getColoredString("|", "light_red") . "                           
       " . $colors->getColoredString("/", "blue") . $colors->getColoredString("      / /\ \     ", "yellow") . $colors->getColoredString("/", "blue") . $colors->getColoredString("|§|/'", "green") . $colors->getColoredString("                     /      ", "green") . $colors->getColoredString("/ /\ \     ", "yellow") . $colors->getColoredString("/", "green") . $colors->getColoredString("|§|/'", "blue") . $colors->getColoredString("                     /", "cyan") . $colors->getColoredString("      / /\ \     ", "yellow") . $colors->getColoredString("/", "cyan") . $colors->getColoredString("|§|/'", "light_red") . $colors->getColoredString("                      /", "light_red") . $colors->getColoredString("      / /\ \     ", "yellow") . $colors->getColoredString("/", "light_red") . $colors->getColoredString("|§|/'", "cyan") . "                           
      ". $colors->getColoredString(".------", "blue") . $colors->getColoredString("/ /", "yellow") . $colors->getColoredString("==", "green") . $colors->getColoredString("\ \\", "yellow") . $colors->getColoredString("---.", "blue") . $colors->getColoredString(" |§/ |", "green") . $colors->getColoredString("                    .------", "green") . $colors->getColoredString("/ /", "yellow") . $colors->getColoredString("==", "blue") . $colors->getColoredString("\ \\", "yellow") . $colors->getColoredString("---. ", "green") . $colors->getColoredString("|§/ |", "blue") . $colors->getColoredString("                    .------", "cyan") . $colors->getColoredString("/ /", "yellow"). $colors->getColoredString("==", "light_red") . $colors->getColoredString("\ \\", "yellow") . $colors->getColoredString("---. ", "cyan") . $colors->getColoredString("|§/ |", "light_red") . $colors->getColoredString("                     .------", "light_red") . $colors->getColoredString("/ /", "yellow") . $colors->getColoredString("==", "cyan") . $colors->getColoredString("\ \\", "yellow") . $colors->getColoredString("---. ", "light_red") . $colors->getColoredString("|§/ |", "cyan") . "                        
      " . $colors->getColoredString("|      ", "blue") . $colors->getColoredString("V'", "yellow") . $colors->getColoredString("§||", "green") . $colors->getColoredString(" | |  ", "yellow") . $colors->getColoredString("| ", "blue") . $colors->getColoredString("|/  ,", "green") . $colors->getColoredString("                    |      ", "green") . $colors->getColoredString("V'", "yellow") . $colors->getColoredString("§|| ", "blue") . $colors->getColoredString("| |  ", "yellow") . $colors->getColoredString("| ", "green") . $colors->getColoredString("|/  ,", "blue") . $colors->getColoredString("                    |      ", "cyan") . $colors->getColoredString("V'", "yellow") . $colors->getColoredString("§|| ", "light_red") . $colors->getColoredString("| |  ", "yellow") . $colors->getColoredString("| ", "cyan") . $colors->getColoredString("|/  ,", "light_red") . $colors->getColoredString("                     |      ", "light_red") . $colors->getColoredString("V'", "yellow") . $colors->getColoredString("§|| ", "cyan") . $colors->getColoredString("| |  ", "yellow") . $colors->getColoredString("| ", "light_red") . $colors->getColoredString("|/  ,", "cyan") . "                           
      " . $colors->getColoredString("|      ", "blue") . $colors->getColoredString("||§||  ", "green") . $colors->getColoredString("V", "yellow") . $colors->getColoredString("   | ", "blue") . $colors->getColoredString("/  /", "green") . $colors->getColoredString("|                    ", "blue") . $colors->getColoredString("|      ", "green") . $colors->getColoredString("||§||  ", "blue") . $colors->getColoredString("V   ", "yellow") . $colors->getColoredString("| ", "green") . $colors->getColoredString("/  /", "blue") . $colors->getColoredString("|                    ", "green") . $colors->getColoredString("|      ", "cyan") . $colors->getColoredString("||§||  ", "light_red") . $colors->getColoredString("V   ", "yellow") . $colors->getColoredString("| ", "cyan") . $colors->getColoredString("/  /", "light_red") . $colors->getColoredString("|                     ", "cyan") . $colors->getColoredString("|      ", "light_red") . $colors->getColoredString("||§||  ", "cyan") . $colors->getColoredString("V   ", "yellow") . $colors->getColoredString("| ", "light_red") . $colors->getColoredString("/  /", "cyan") . $colors->getColoredString("|", "light_red") . "                           
      " . $colors->getColoredString("|      ", "blue") . $colors->getColoredString("||§||      ", "green") . $colors->getColoredString("|", "blue") . $colors->getColoredString("/  / ", "green") . $colors->getColoredString("|                    ", "blue") . $colors->getColoredString("|      ", "green") . $colors->getColoredString("||§||      ", "blue") . $colors->getColoredString("|", "green") . $colors->getColoredString("/  / ", "blue") . $colors->getColoredString("|                    ", "green") . $colors->getColoredString("|      ", "cyan") . $colors->getColoredString("||§||      ", "light_red") . $colors->getColoredString("|", "cyan") . $colors->getColoredString("/  / ", "light_red") . $colors->getColoredString("|                     ", "cyan") . $colors->getColoredString("|      ", "light_red") . $colors->getColoredString("||§||      ", "cyan") . $colors->getColoredString("|", "light_red") . $colors->getColoredString("/  / ", "cyan") . $colors->getColoredString("|", "light_red") . "                           
      " . $colors->getColoredString(",=================,", "green") . $colors->getColoredString("  /| ", "green") .$colors->getColoredString("|                    ", "blue") . $colors->getColoredString(",=================,", "blue") . $colors->getColoredString("  /| ", "blue") . $colors->getColoredString("|                    ", "green") . $colors->getColoredString(",=================,", "light_red") . $colors->getColoredString("  /| ", "light_red") . $colors->getColoredString("|                     ", "cyan") . $colors->getColoredString(",=================,", "cyan") . $colors->getColoredString("  /| ", "cyan") . $colors->getColoredString("|", "light_red") . "                           
      " . $colors->getColoredString("|                 | /§|", "green") . $colors->getColoredString("/                     ", "blue") . $colors->getColoredString("|                 | /§|", "blue") . $colors->getColoredString("/                     ", "green") . $colors->getColoredString("|                 | /§|", "light_red") . $colors->getColoredString("/                      ", "cyan") . $colors->getColoredString("|                 | /§|", "cyan") . $colors->getColoredString("/", "light_red") . "                            
      " . $colors->getColoredString("`=================`", "green") . $colors->getColoredString("/|§", "green") . $colors->getColoredString("/                      ", "blue") . $colors->getColoredString("`=================`", "blue") . $colors->getColoredString("/|§", "blue") . $colors->getColoredString("/                      ", "green") . $colors->getColoredString("`=================`", "light_red") . $colors->getColoredString("/|§", "light_red") .$colors->getColoredString("/                       ", "cyan") . $colors->getColoredString("`=================`", "cyan") . $colors->getColoredString("/|§", "cyan") . $colors->getColoredString("/", "light_red") . "                             
      " . $colors->getColoredString("|      ", "blue") . $colors->getColoredString("||§||      ", "green") . $colors->getColoredString("| ", "blue") . $colors->getColoredString("|", "green") . $colors->getColoredString("/                       ", "blue") . $colors->getColoredString("|      ", "green") . $colors->getColoredString("||§||      ", "blue") . $colors->getColoredString("| ", "green") . $colors->getColoredString("|", "blue") . $colors->getColoredString("/                       ", "green") . $colors->getColoredString("|      ", "cyan") . $colors->getColoredString("||§||      ", "light_red") . $colors->getColoredString("| ", "cyan") . $colors->getColoredString("|", "light_red") . $colors->getColoredString("/                        ", "cyan") . $colors->getColoredString("|      ", "light_red") . $colors->getColoredString("||§||      ", "cyan") . $colors->getColoredString("| ", "light_red") . $colors->getColoredString("|", "cyan") . $colors->getColoredString("/", "light_red") . "                              
      " . $colors->getColoredString("|      ", "blue") . $colors->getColoredString("||§||      ", "green") . $colors->getColoredString("| /                        ", "blue") . $colors->getColoredString("|      ", "green") . $colors->getColoredString("||§||      ", "blue") . $colors->getColoredString("| /                        ", "green") . $colors->getColoredString("|      ", "blue") . $colors->getColoredString("||§||      ", "light_red") . $colors->getColoredString("| /                         ", "cyan") . $colors->getColoredString("|      ", "light_red") . $colors->getColoredString("||§||      ", "cyan") . $colors->getColoredString("| /", "light_red") . "                               
      " . $colors->getColoredString("|      ", "blue") . $colors->getColoredString("||§||      ", "green") . $colors->getColoredString("|/                         ", "blue") . $colors->getColoredString("|      ", "green") . $colors->getColoredString("||§||      ", "blue") . $colors->getColoredString("|/                         ", "green") . $colors->getColoredString("|      ", "cyan") . $colors->getColoredString("||§||      ", "light_red") . $colors->getColoredString("|/                          ", "cyan") . $colors->getColoredString("|      ", "light_red") . $colors->getColoredString("||§||      ", "cyan") . $colors->getColoredString("|/", "light_red") . "                                
      ". $colors->getColoredString("'------", "blue") . $colors->getColoredString("=====", "green") . $colors->getColoredString("------'                          ", "blue") . $colors->getColoredString("'------", "green") . $colors->getColoredString("=====", "blue") . $colors->getColoredString("------'                          ", "green") . $colors->getColoredString("'------", "cyan") . $colors->getColoredString("=====", "light_red") . $colors->getColoredString("------'                           ", "cyan") . $colors->getColoredString("'------", "light_red") . $colors->getColoredString("=====", "cyan") . $colors->getColoredString("------'", "light_red") . "                                 
";